# -*- coding: utf-8 -*-
# WARNING: Autogenerated code. Do not edit manually. Regenerate with codegen.py


class Getblockchaininfo:

    def __init__(self, **kwargs):
        self._kwargs = kwargs
        self.protocol = kwargs["protocol"]
        self.reindex = kwargs["reindex"]
        self.chainname = kwargs["chainname"]
        self.setupblocks = kwargs["setupblocks"]
        self.chain = kwargs["chain"]
        self.description = kwargs["description"]
        self.blocks = kwargs["blocks"]
        self.verificationprogress = kwargs["verificationprogress"]
        self.bestblockhash = kwargs["bestblockhash"]
        self.difficulty = kwargs["difficulty"]
        self.chainwork = kwargs["chainwork"]
        self.headers = kwargs["headers"]
    
    def as_dict(self):
        return self._kwargs
        
    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self._kwargs == other._kwargs
        else:
            return False


class Getinfo:

    def __init__(self, **kwargs):
        self._kwargs = kwargs
        self.keypoololdest = kwargs["keypoololdest"]
        self.protocol = kwargs["protocol"]
        self.incomingpaused = kwargs["incomingpaused"]
        self.chainname = kwargs["chainname"]
        self.setupblocks = kwargs["setupblocks"]
        self.balance = kwargs["balance"]
        self.nodeversion = kwargs["nodeversion"]
        self.blocks = kwargs["blocks"]
        self.keypoolsize = kwargs["keypoolsize"]
        self.reindex = kwargs["reindex"]
        self.miningpaused = kwargs["miningpaused"]
        self.difficulty = kwargs["difficulty"]
        self.proxy = kwargs["proxy"]
        self.testnet = kwargs["testnet"]
        self.protocolversion = kwargs["protocolversion"]
        self.port = kwargs["port"]
        self.version = kwargs["version"]
        self.description = kwargs["description"]
        self.connections = kwargs["connections"]
        self.timeoffset = kwargs["timeoffset"]
        self.errors = kwargs["errors"]
        self.paytxfee = kwargs["paytxfee"]
        self.walletdbversion = kwargs["walletdbversion"]
        self.burnaddress = kwargs["burnaddress"]
        self.walletversion = kwargs["walletversion"]
        self.nodeaddress = kwargs["nodeaddress"]
        self.relayfee = kwargs["relayfee"]
    
    def as_dict(self):
        return self._kwargs
        
    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self._kwargs == other._kwargs
        else:
            return False


class Getruntimeparams:

    def __init__(self, **kwargs):
        self._kwargs = kwargs
        self.autocombinemaxinputs = kwargs["autocombinemaxinputs"]
        self.lockblock = kwargs["lockblock"]
        self.gen = kwargs["gen"]
        self.reindex = kwargs["reindex"]
        self.bantx = kwargs["bantx"]
        self.hideknownopdrops = kwargs["hideknownopdrops"]
        self.miningrequirespeers = kwargs["miningrequirespeers"]
        self.port = kwargs["port"]
        self.autocombineminconf = kwargs["autocombineminconf"]
        self.mineemptyrounds = kwargs["mineemptyrounds"]
        self.genproclimit = kwargs["genproclimit"]
        self.maxshowndata = kwargs["maxshowndata"]
        self.txindex = kwargs["txindex"]
        self.miningturnover = kwargs["miningturnover"]
        self.handshakelocal = kwargs["handshakelocal"]
        self.autocombinedelay = kwargs["autocombinedelay"]
        self.lockadminminerounds = kwargs["lockadminminerounds"]
        self.autosubscribe = kwargs["autosubscribe"]
        self.rescan = kwargs["rescan"]
        self.autocombinesuspend = kwargs["autocombinesuspend"]
        self.autocombinemininputs = kwargs["autocombinemininputs"]
    
    def as_dict(self):
        return self._kwargs
        
    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self._kwargs == other._kwargs
        else:
            return False
