# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Patricia\Desktop\GUI COBLO\gui-demo\app/ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 588)
        MainWindow.setMinimumSize(QtCore.QSize(640, 400))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layout_main = QtWidgets.QHBoxLayout(self.centralwidget)
        self.layout_main.setContentsMargins(0, 0, 0, 0)
        self.layout_main.setObjectName("layout_main")
        self.frame_sidebar = QtWidgets.QFrame(self.centralwidget)
        self.frame_sidebar.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_sidebar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_sidebar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sidebar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_sidebar.setObjectName("frame_sidebar")
        self.layout_frame_sidebar = QtWidgets.QVBoxLayout(self.frame_sidebar)
        self.layout_frame_sidebar.setContentsMargins(0, 0, 0, 0)
        self.layout_frame_sidebar.setObjectName("layout_frame_sidebar")
        self.frame_sidebar_header = QtWidgets.QFrame(self.frame_sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sidebar_header.sizePolicy().hasHeightForWidth())
        self.frame_sidebar_header.setSizePolicy(sizePolicy)
        self.frame_sidebar_header.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_sidebar_header.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_sidebar_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sidebar_header.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_sidebar_header.setLineWidth(0)
        self.frame_sidebar_header.setObjectName("frame_sidebar_header")
        self.layout_side_bar_header = QtWidgets.QVBoxLayout(self.frame_sidebar_header)
        self.layout_side_bar_header.setObjectName("layout_side_bar_header")
        self.label_app_title = QtWidgets.QLabel(self.frame_sidebar_header)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_app_title.setFont(font)
        self.label_app_title.setObjectName("label_app_title")
        self.layout_side_bar_header.addWidget(self.label_app_title)
        self.btn_get_coins = QtWidgets.QPushButton(self.frame_sidebar_header)
        self.btn_get_coins.setObjectName("btn_get_coins")
        self.layout_side_bar_header.addWidget(self.btn_get_coins)
        self.layout_frame_sidebar.addWidget(self.frame_sidebar_header)
        self.line_sidebar_top = QtWidgets.QFrame(self.frame_sidebar)
        self.line_sidebar_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_sidebar_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_sidebar_top.setObjectName("line_sidebar_top")
        self.layout_frame_sidebar.addWidget(self.line_sidebar_top)
        self.frame_sidebar_nav = QtWidgets.QFrame(self.frame_sidebar)
        self.frame_sidebar_nav.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sidebar_nav.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_sidebar_nav.setLineWidth(0)
        self.frame_sidebar_nav.setObjectName("frame_sidebar_nav")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_sidebar_nav)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_nav_wallet = QtWidgets.QPushButton(self.frame_sidebar_nav)
        self.btn_nav_wallet.setCheckable(True)
        self.btn_nav_wallet.setChecked(True)
        self.btn_nav_wallet.setObjectName("btn_nav_wallet")
        self.btn_group_nav = QtWidgets.QButtonGroup(MainWindow)
        self.btn_group_nav.setObjectName("btn_group_nav")
        self.btn_group_nav.addButton(self.btn_nav_wallet)
        self.verticalLayout.addWidget(self.btn_nav_wallet)
        self.btn_nav_community = QtWidgets.QPushButton(self.frame_sidebar_nav)
        self.btn_nav_community.setCheckable(True)
        self.btn_nav_community.setChecked(False)
        self.btn_nav_community.setObjectName("btn_nav_community")
        self.btn_group_nav.addButton(self.btn_nav_community)
        self.verticalLayout.addWidget(self.btn_nav_community)
        self.layout_frame_sidebar.addWidget(self.frame_sidebar_nav, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(0, 1600000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_frame_sidebar.addItem(spacerItem)
        self.line_sidebar_bottom = QtWidgets.QFrame(self.frame_sidebar)
        self.line_sidebar_bottom.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_sidebar_bottom.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_sidebar_bottom.setObjectName("line_sidebar_bottom")
        self.layout_frame_sidebar.addWidget(self.line_sidebar_bottom)
        self.frame_sidebar_footer = QtWidgets.QFrame(self.frame_sidebar)
        self.frame_sidebar_footer.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_sidebar_footer.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_sidebar_footer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sidebar_footer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_sidebar_footer.setObjectName("frame_sidebar_footer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_sidebar_footer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_blockchain_sync = QtWidgets.QLabel(self.frame_sidebar_footer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_blockchain_sync.setFont(font)
        self.label_blockchain_sync.setObjectName("label_blockchain_sync")
        self.verticalLayout_3.addWidget(self.label_blockchain_sync)
        self.progbar_blockchain_sync = QtWidgets.QProgressBar(self.frame_sidebar_footer)
        self.progbar_blockchain_sync.setProperty("value", 24)
        self.progbar_blockchain_sync.setInvertedAppearance(False)
        self.progbar_blockchain_sync.setObjectName("progbar_blockchain_sync")
        self.verticalLayout_3.addWidget(self.progbar_blockchain_sync)
        self.layout_frame_sidebar.addWidget(self.frame_sidebar_footer)
        self.layout_main.addWidget(self.frame_sidebar)
        self.line_sidebar_right = QtWidgets.QFrame(self.centralwidget)
        self.line_sidebar_right.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_sidebar_right.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_sidebar_right.setObjectName("line_sidebar_right")
        self.layout_main.addWidget(self.line_sidebar_right)
        self.stack_content = QtWidgets.QStackedWidget(self.centralwidget)
        self.stack_content.setObjectName("stack_content")
        self.page_wallet = QtWidgets.QWidget()
        self.page_wallet.setObjectName("page_wallet")
        self.layout_page_wallet = QtWidgets.QVBoxLayout(self.page_wallet)
        self.layout_page_wallet.setContentsMargins(9, 9, 18, 0)
        self.layout_page_wallet.setSpacing(12)
        self.layout_page_wallet.setObjectName("layout_page_wallet")
        self.layout_wallet_header = QtWidgets.QHBoxLayout()
        self.layout_wallet_header.setContentsMargins(-1, 0, -1, -1)
        self.layout_wallet_header.setSpacing(20)
        self.layout_wallet_header.setObjectName("layout_wallet_header")
        self.label_wallet_title = QtWidgets.QLabel(self.page_wallet)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_wallet_title.setFont(font)
        self.label_wallet_title.setObjectName("label_wallet_title")
        self.layout_wallet_header.addWidget(self.label_wallet_title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_wallet_header.addItem(spacerItem1)
        self.layout_wallet_address = QtWidgets.QVBoxLayout()
        self.layout_wallet_address.setSpacing(0)
        self.layout_wallet_address.setObjectName("layout_wallet_address")
        self.label_wallet_address_title = QtWidgets.QLabel(self.page_wallet)
        self.label_wallet_address_title.setObjectName("label_wallet_address_title")
        self.layout_wallet_address.addWidget(self.label_wallet_address_title)
        self.label_wallet_address = QtWidgets.QLabel(self.page_wallet)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_wallet_address.setFont(font)
        self.label_wallet_address.setScaledContents(False)
        self.label_wallet_address.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_wallet_address.setObjectName("label_wallet_address")
        self.layout_wallet_address.addWidget(self.label_wallet_address)
        self.layout_wallet_header.addLayout(self.layout_wallet_address)
        self.layout_wallet_balance = QtWidgets.QVBoxLayout()
        self.layout_wallet_balance.setSpacing(0)
        self.layout_wallet_balance.setObjectName("layout_wallet_balance")
        self.label_wallet_balance_title = QtWidgets.QLabel(self.page_wallet)
        self.label_wallet_balance_title.setObjectName("label_wallet_balance_title")
        self.layout_wallet_balance.addWidget(self.label_wallet_balance_title)
        self.label_wallet_balance = QtWidgets.QLabel(self.page_wallet)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_wallet_balance.setFont(font)
        self.label_wallet_balance.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_wallet_balance.setObjectName("label_wallet_balance")
        self.layout_wallet_balance.addWidget(self.label_wallet_balance)
        self.layout_wallet_header.addLayout(self.layout_wallet_balance)
        self.layout_page_wallet.addLayout(self.layout_wallet_header)
        self.frame_wallet_send = QtWidgets.QFrame(self.page_wallet)
        self.frame_wallet_send.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_wallet_send.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_wallet_send.setObjectName("frame_wallet_send")
        self.layout_wallet_send = QtWidgets.QVBoxLayout(self.frame_wallet_send)
        self.layout_wallet_send.setContentsMargins(0, 0, 0, 0)
        self.layout_wallet_send.setObjectName("layout_wallet_send")
        self.layout_page_wallet.addWidget(self.frame_wallet_send)
        self.frame_wallet_history = QtWidgets.QFrame(self.page_wallet)
        self.frame_wallet_history.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_wallet_history.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_wallet_history.setObjectName("frame_wallet_history")
        self.layout_wallet_history = QtWidgets.QVBoxLayout(self.frame_wallet_history)
        self.layout_wallet_history.setContentsMargins(0, 0, 0, 0)
        self.layout_wallet_history.setObjectName("layout_wallet_history")
        self.layout_page_wallet.addWidget(self.frame_wallet_history)
        self.layout_page_wallet.setStretch(2, 1)
        self.stack_content.addWidget(self.page_wallet)
        self.page_community = QtWidgets.QWidget()
        self.page_community.setObjectName("page_community")
        self.layout_community = QtWidgets.QVBoxLayout(self.page_community)
        self.layout_community.setContentsMargins(0, 0, 0, 0)
        self.layout_community.setObjectName("layout_community")
        self.label = QtWidgets.QLabel(self.page_community)
        self.label.setText("")
        self.label.setObjectName("label")
        self.layout_community.addWidget(self.label)
        self.stack_content.addWidget(self.page_community)
        self.page_privilege_requests = QtWidgets.QWidget()
        self.page_privilege_requests.setObjectName("page_privilege_requests")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_privilege_requests)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stack_content.addWidget(self.page_privilege_requests)
        self.layout_main.addWidget(self.stack_content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stack_content.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_get_coins, self.btn_nav_wallet)
        MainWindow.setTabOrder(self.btn_nav_wallet, self.btn_nav_community)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Charm"))
        self.label_app_title.setText(_translate("MainWindow", "Charm"))
        self.btn_get_coins.setText(_translate("MainWindow", "Get Coins Now"))
        self.btn_nav_wallet.setText(_translate("MainWindow", "Wallet"))
        self.btn_nav_community.setText(_translate("MainWindow", "Community"))
        self.label_blockchain_sync.setText(_translate("MainWindow", "Blockchain sync"))
        self.label_wallet_title.setText(_translate("MainWindow", "Wallet"))
        self.label_wallet_address_title.setText(_translate("MainWindow", "Main Address"))
        self.label_wallet_address.setText(_translate("MainWindow", "00000000000000000000000"))
        self.label_wallet_balance_title.setText(_translate("MainWindow", "Total Balance"))
        self.label_wallet_balance.setText(_translate("MainWindow", "0,00 CHM"))

