# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smartlicense.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='smartlicense.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12smartlicense.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x02\n\x0cSmartLicense\x12\x11\n\tlicensors\x18\x01 \x03(\t\x12\x11\n\tmaterials\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12%\n\x0erights_profile\x18\x04 \x03(\x0e\x32\r.RightsModule\x12)\n\x10\x61\x63tivation_modes\x18\x05 \x03(\x0e\x32\x0f.ActivationMode\x12\x16\n\x0eon_chain_price\x18\x06 \x01(\x01\x12 \n\x10off_chain_prices\x18\x07 \x03(\x0b\x32\x06.Price\x12\x17\n\x0fpayment_address\x18\x08 \x01(\t\x12+\n\x08\x64uration\x18\t \x01(\x0b\x32\x19.google.protobuf.Duration\x12.\n\nstart_time\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bterritories\x18\x0b \x03(\t\x12\x12\n\naccess_url\x18\x0c \x01(\t\")\n\x05Price\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t*\x97\x01\n\x0cRightsModule\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\t\n\x05\x41\x44\x41PT\x10\x01\x12\x08\n\x04LEND\x10\x02\x12\r\n\tREPRODUCE\x10\x03\x12\n\n\x06RESALE\x10\x04\x12\t\n\x05SHARE\x10\x05\x12\x12\n\x0eNON_COMMERCIAL\x10\x06\x12\x0f\n\x0b\x41TTRIBUTION\x10\x07\x12\x16\n\x12INDICATE_ADAPTIONS\x10\x08*@\n\x0e\x41\x63tivationMode\x12\x14\n\x10ON_CHAIN_PAYMENT\x10\x00\x12\x18\n\x14ON_CHAIN_ATTESTATION\x10\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_RIGHTSMODULE = _descriptor.EnumDescriptor(
  name='RightsModule',
  full_name='RightsModule',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADAPT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEND', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPRODUCE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESALE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHARE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NON_COMMERCIAL', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATTRIBUTION', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDICATE_ADAPTIONS', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=506,
  serialized_end=657,
)
_sym_db.RegisterEnumDescriptor(_RIGHTSMODULE)

RightsModule = enum_type_wrapper.EnumTypeWrapper(_RIGHTSMODULE)
_ACTIVATIONMODE = _descriptor.EnumDescriptor(
  name='ActivationMode',
  full_name='ActivationMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ON_CHAIN_PAYMENT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_CHAIN_ATTESTATION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=659,
  serialized_end=723,
)
_sym_db.RegisterEnumDescriptor(_ACTIVATIONMODE)

ActivationMode = enum_type_wrapper.EnumTypeWrapper(_ACTIVATIONMODE)
UNSPECIFIED = 0
ADAPT = 1
LEND = 2
REPRODUCE = 3
RESALE = 4
SHARE = 5
NON_COMMERCIAL = 6
ATTRIBUTION = 7
INDICATE_ADAPTIONS = 8
ON_CHAIN_PAYMENT = 0
ON_CHAIN_ATTESTATION = 1



_SMARTLICENSE = _descriptor.Descriptor(
  name='SmartLicense',
  full_name='SmartLicense',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='licensors', full_name='SmartLicense.licensors', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='materials', full_name='SmartLicense.materials', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='SmartLicense.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rights_profile', full_name='SmartLicense.rights_profile', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_modes', full_name='SmartLicense.activation_modes', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='on_chain_price', full_name='SmartLicense.on_chain_price', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='off_chain_prices', full_name='SmartLicense.off_chain_prices', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment_address', full_name='SmartLicense.payment_address', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='SmartLicense.duration', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='SmartLicense.start_time', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='territories', full_name='SmartLicense.territories', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='access_url', full_name='SmartLicense.access_url', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=460,
)


_PRICE = _descriptor.Descriptor(
  name='Price',
  full_name='Price',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='Price.amount', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='Price.currency', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=503,
)

_SMARTLICENSE.fields_by_name['rights_profile'].enum_type = _RIGHTSMODULE
_SMARTLICENSE.fields_by_name['activation_modes'].enum_type = _ACTIVATIONMODE
_SMARTLICENSE.fields_by_name['off_chain_prices'].message_type = _PRICE
_SMARTLICENSE.fields_by_name['duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_SMARTLICENSE.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['SmartLicense'] = _SMARTLICENSE
DESCRIPTOR.message_types_by_name['Price'] = _PRICE
DESCRIPTOR.enum_types_by_name['RightsModule'] = _RIGHTSMODULE
DESCRIPTOR.enum_types_by_name['ActivationMode'] = _ACTIVATIONMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmartLicense = _reflection.GeneratedProtocolMessageType('SmartLicense', (_message.Message,), dict(
  DESCRIPTOR = _SMARTLICENSE,
  __module__ = 'smartlicense_pb2'
  # @@protoc_insertion_point(class_scope:SmartLicense)
  ))
_sym_db.RegisterMessage(SmartLicense)

Price = _reflection.GeneratedProtocolMessageType('Price', (_message.Message,), dict(
  DESCRIPTOR = _PRICE,
  __module__ = 'smartlicense_pb2'
  # @@protoc_insertion_point(class_scope:Price)
  ))
_sym_db.RegisterMessage(Price)


# @@protoc_insertion_point(module_scope)
